### ISSUE TITLE
spbot项目打包失败

### ISSUE THREAD

**Issue by daofeng2015** [guyijie1211/MixLive#1]
![QQ截图20210603002220](https://user-images.githubusercontent.com/14891398/120516667-2f735b80-c402-11eb-9bf3-08f55dda5843.png)

然后我安装网上搜到的教程
![image](https://user-images.githubusercontent.com/14891398/120516565-166aaa80-c402-11eb-8397-436ec1dc22dc.png)cha尝试解决,还是解决不了...

**Comment by guyijie1211** [comment]
我更新了pom文件，把maven-resources-plugin版本设为2.6后就能打包了，你试试。具体为啥我也不清楚。

**Comment by daofeng2015** [comment]
> 我更新了pom文件，把maven-resources-plugin版本设为2.6后就能打包了，你试试。具体为啥我也不清楚。

打包成功了...ok了
